### ISSUE TITLE
[Targeted Messaging] the 'Subscribe Today' black&white ad/template not resized correctly

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#10]
the 'Subscribe Today' black&white ad/template not resized correctly.  text is overlapping over each other.  see screen shot:
![screen shot 2016-12-15 at 11 17 13 am](https://cloud.githubusercontent.com/assets/20052632/21232269/09e45f58-c2b9-11e6-979b-237138627228.png)

**Comment by mkoza178** [comment]
Hey guys,

This is fixed. Please use the small templates seen in the screenshot. http://prnt.sc/dk7prv
You'll need to update in the admin first.

**Comment by kamini1208** [comment]
closing issue.  verified template resized.
