### ISSUE TITLE
[eCommerce Abandonment] Conversations do not display on Handheld devices

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#11]
on Handheld devices (mobile and tablets), conversations do not display at all.  See Screen Shot:
![img_2206](https://cloud.githubusercontent.com/assets/20052632/21316554/45b5fc44-c5cf-11e6-9a8e-849aa7a88c1a.png)

**Comment by mg2dael** [comment]
It looks like all your conversations are currently built with a "hover" for when it is shown. http://prntscr.com/dlghto Since mobile devices have no mouse, there's no hover.

**Comment by mg2dael** [comment]
Sorry, hit the wrong button. Didn't mean to close.

**Comment by kamini1208** [comment]
closing issue. This is a MG2 Admin config setting.
