### ISSUE TITLE
[Targeted Messaging] onActionClosed target

### ISSUE THREAD

**Issue by willist** [mg2connext/connext#12]
When `onActionClosed` fires, is it possible to determine how it was closed?

For metrics purposes, we would like to know if a user clicked the X button, No Thanks, or the dark overlay around the modal. If a form field is available and the user completes the form, we would like to be able to track that as well.

Is this currently available or something that could be added?

**Comment by mg2dael** [comment]
We're investigating adding this information to the `onActionClosed` event. We are testing a solution currently and hope to make it available soon. I'll update once it's public.

**Comment by mg2dael** [comment]
We'll be adding `closeEvent` to `onActionClosed` which will return four possible values:

- `closeButton `  (close button)
- `closeSpan`    (no thanks link)
- `clickOutside`  (backdrop)
- `escButton`  (escape)

This is currently in our dev environment and being tested. We expect to release it to all other environments early next week.

**Comment by mg2dael** [comment]
This is now populated to all environments.

If you have debug mode off you won't see them in the console, but you should be able to get the data from your analytics software.
