### ISSUE TITLE
Error during script load

### ISSUE THREAD

**Issue by willist** [mg2connext/connext#13]
While trying to load `https://mg2assetsdev.blob.core.windows.net/connext/test/1.0/Connext.min.js`, I'm seeing the error:

```
Uncaught TypeError: Cannot read property '_' of undefined
    at Connext.min.js:11
    at Connext.min.js:11
```

**Comment by mg2dael** [comment]
It looks like this is caused when our code repo does the JS minification. It works fine before we minify, though. We're investigating what changed in the system that this is now happening (since it was fine before).

**Comment by sframe** [comment]
Looks like this is resolved? Can we double check everywhere this could be an issue?

**Comment by mg2dael** [comment]
We think it's fixed, but we're doing the double check. I'm hoping for final clearance today at which point we can close this.

**Comment by sframe** [comment]
Thanks @mg2dael :)

**Comment by mg2dael** [comment]
@sframe 
We can close this if you'd like. They switched what minifier they're using until we figure out why the our normal one is broken.

**Comment by sframe** [comment]
Closing as it appears that it is loading correctly again :)
