### ISSUE TITLE
localStorage shim is causing issues with IE11

### ISSUE THREAD

**Issue by zenparsing** [mg2connext/connext#15]
We're seeing severe issues with our website in IE when it loads `Connext.min.js`.

`Connext.min.js` contains the following code:

```js
n = localStorage.removeItem;
localStorage.removeItem = function () {
  n.apply(this, arguments)
};
```

In IE11, this causes `localStorage.removeItem` to be set to a string value. Our website code is throwing exceptions in IE when it attempts to interact with local storage.

Please do not overwrite or attempt to shim `window.localStorage`. Otherwise, we will not be able to deploy this code.

**Comment by sframe** [comment]
Hey @mg2dael, can you give some feedback on this issue? It's affecting our Member Center work.

Thanks!

**Comment by mg2dael** [comment]
@sframe I've asked the devs to look into it during their morning tomorrow. @NatalliaMikhailava can you please make sure they know this is high priority?

**Comment by sframe** [comment]
Thanks ^_^

**Comment by mg2dael** [comment]
@sframe and @zenparsing  We've got it fixed. The team is working on populating it into all our environments in Azure. At the latest you should see the fix tomorrow.
