### ISSUE TITLE
onActionShown firing twice

### ISSUE THREAD

**Issue by willist** [mg2connext/connext#16]
In Test Environment, using Campaign `MEMBER CENTER'S SUPER AWESOME TEST TEST`:

Modal appears to flash when user navigates to http://membercenter-dev-metrics.aws.cmgdigital.com/newsletters and `onActionShown` fires twice.

**Comment by mg2dael** [comment]
@willist We're looking into it.

**Comment by mg2dael** [comment]
@willist I think I know what's going on, but I need to wait for a developer to confirm on Monday.

**Comment by mg2dael** [comment]
@willist When I had one of our devs goes through the site, they saw that you've calling `connext.Run()` twice http://prnt.sc/e25u8t and http://prnt.sc/e25v4k This appears to be what's causing the double fire of `onActionShown` and the flash.
