### ISSUE TITLE
Updating from Connext `1.1` to `1.3`

### ISSUE THREAD

**Issue by sframe** [mg2connext/connext#18]
Hey Team MG2,

I'm working on a task to update our Prod instance from Connext `1.1` to `1.3` and I noticed and error in the console:

`Connext >>>> DEBUG <<<<< API => GetLastPublishDateS3 => jsonURL => https://s3.amazonaws.com/connext.prod/data/last_publish/AJC.json`
`Failed to load resource: the server responded with a status of 403 (Forbidden)`

Not sure if this something for me to be worried about before promoting to prod.

**Comment by sframe** [comment]
Snippet from our configs:

```json
{
  "plugins": {
    "connext": {
      "environment:prod": "prod",
      "script_url:prod": "//cdn.mg2connext.com/prod/1.3/Connext.min.js",
      "stylesheet_url:prod": "//cdn.mg2connext.com/prod/1.3/Connext.min.css"
    }
  }
}
```

**Comment by sframe** [comment]
And loading another tenant, "Palm Beach Post":

`Connext.min.js:31 Connext >>>> DEBUG <<<<< API => GetLastPublishDateS3 => jsonURL => https://s3.amazonaws.com/connext.prod/data/last_publish/PO.json`

`GET https://s3.amazonaws.com/connext.prod/data/last_publish/PO.json 403 (Forbidden)`

**Comment by sframe** [comment]
Maybe it's an AWS S3 permission thing?

```html
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>FB2C5D9AEE1BD0D2</RequestId><HostId>0cQ2aZ3lvjEHw19H7l9AWsLR5j8r2JTTy3IU7tJqMBFOWGyXbUBh/YQk3ncgTphqiQJJqtxF8W0=</HostId></Error>
```

**Comment by sframe** [comment]
I think I may have misread the comment from @NatalliaMikhailava at https://github.com/mg2connext/connext/issues/17

Which is latest stable version of Connext we should have loaded in our prod environments?

<sup>Sorry for the comment spam!</sup>

**Comment by sframe** [comment]
Hey @mg2dael :) 

Which Connext version _should_ we be linking against now?

**Comment by mg2dael** [comment]
@sframe Sorry, I'm a bit confused.  Issue 17 was referring to stage afaict which you are now using 1.6 (which is right for stage).  For prod, there shouldn't have been any need to change until we had 1.6 ready for you in prod.  Is there a reason why we're changing the prod links to 1.3 now?

**Comment by sframe** [comment]
@mg2dael: I may be overreacting to Natallia's comment to upgrade Connext :)

If you're confirming that 1.1 is appropriate for Prod then I'll kill out our current ticket.

**Comment by mg2dael** [comment]
@sframe 1.1 is fine for Prod. You may want to plan a ticket to upgrade to 1.6 in a few weeks once Gwen is ready for the new features, but we'll keep supporting 1.1 until that point.

**Comment by sframe** [comment]
Sounds great thanks @mg2dael
