### ISSUE TITLE
Need Janrain login template versions for banner and roadblock (should have 2 versions one with log in , 1 without)

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#19]
![image](https://user-images.githubusercontent.com/20052632/27304579-7f15fc2e-550c-11e7-8152-14df03dfe2d3.png)

**Comment by mkoza178** [comment]
I do not see a template for a login version in the original PSDs. @mg2dael do you have one?

**Comment by mg2dael** [comment]
There wasn’t one.  We’re just changing the existing link/button to pop up the janrain modal.

-------------------------------------------------------
Dael Jackson
Product/Project Manager, Marketing G2
djackson@marketingg2.com<mailto:djackson@marketingg2.com>
Results through Marketing Intelligence
[Description: Description: Description: cid:AC478EE2-0CEC-442F-9511-E62E72518DA7]
Follow Marketing G2:
[Facebook Icon]<https://www.facebook.com/MarketingG2/>[Twitter Icon]<https://twitter.com/MarketingG2>[LinkedIn Icon]<https://www.linkedin.com/company-beta/1285481/>

**Comment by mg2dael** [comment]
There are now two new templates available in stage: paywall_roadblock_cmg_login and banner_rotate_cmg_login

**Comment by mg2dael** [comment]
@kamini1208 Can we close this issue?

**Comment by kamini1208** [comment]
closing ticket
