### ISSUE TITLE
Having issues changing images.  Can you send the actually images used, so we can replicate for Springfield

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#20]
![image](https://user-images.githubusercontent.com/20052632/27304609-9f09b61a-550c-11e7-99fd-f9469449a98a.png)
a.       Banner image doesn’t display well
b.      Roadblock image cuts off image on 2nd and 3rd images
c.       Welcome Image is ok, but a little to the right

**Comment by mg2dael** [comment]
We followed the handling of images from the PSDs.  This includes the vertical positioning rules which seem to be most of what is causing Gwen problems.  @mkoza178 knows how to manipulate the positioning and would be willing to assist.

**Comment by mkoza178** [comment]
Gwen has requested the original PSDs we used. I have sent to her.

**Comment by mkoza178** [comment]
I also showed her how we manually moved images via inspect and the browser console.

**Comment by kamini1208** [comment]
closing ticket
