### ISSUE TITLE
Unable to use multiple javascript variables.

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#21]
![image](https://user-images.githubusercontent.com/20052632/27304671-d8de3168-550c-11e7-84cd-11262e8ce095.png)

**Comment by mg2dael** [comment]
We're working on a patch but it won't be available before your desired go live.  We can create the code to combine more than one JS variable and input it for you, but we'd need details on what specifically you're hoping to do on each action.

**Comment by mkoza178** [comment]
Right now we are working with Gwen. 
Awaiting the details back from her on the JS variables for each action.

**Comment by kamini1208** [comment]
Springfield.com_Default
Assumption is that I don’t need to include membercenter.connextData.referrerType not= Search,  since it is in the Dynamic meter and will not trigger article count and/or Meter setting.
 
Welcome 1 – Modal Non Social/Search Logged Out
![image](https://user-images.githubusercontent.com/20052632/27397564-c65c3b10-5684-11e7-82e5-4895bbdb22a0.png)
membercenter.connextData.referrerType = “”
membercenter.connextData.isAuthenticated = false
articleviews = 1

Welcome 1a – Modal Non Social/Search Logged In Non Sub
![image](https://user-images.githubusercontent.com/20052632/27397577-d52e8468-5684-11e7-94e9-40aaf183bccb.png)
membercenter.connextData.referrerType = “”
membercenter.connextData.isAuthenticated = true
membercenter.connextData.isSubscriber = false
articleviews = 1

Welcome 2 – Modal Social Logged Out
membercenter.connextData.referrerType = Social
membercenter.connextData.isAuthenticated = false
articleviews = 2
![image](https://user-images.githubusercontent.com/20052632/27397592-e73db8a4-5684-11e7-9008-da2801b31179.png)

Login 3 - Banner: Non Logged In
![image](https://user-images.githubusercontent.com/20052632/27397604-f1856c12-5684-11e7-850d-96132586b4e6.png)
membercenter.connextData.isAuthenticated = false
articleviews = 3

Subscribe 3 - Banner: Logged in Non Subscribers
![image](https://user-images.githubusercontent.com/20052632/27397631-00e697b2-5685-11e7-8c02-a30074b1c63f.png)
membercenter.connextData.isAuthenticated = true
membercenter.connextData.isSubscriber = false
articleviews = 3

Subscribe 7 - Banner: Non Subscriber
![image](https://user-images.githubusercontent.com/20052632/27397660-14cb2cd4-5685-11e7-913b-f54c1d4948f5.png)
membercenter.connextData.isSubscriber = false
articleviews = 7

Roadblock 9 - Paywall: Non Subscriber
membercenter.connextData.isAuthorized = false
articleviews >=9
![image](https://user-images.githubusercontent.com/20052632/27397677-224de1e4-5685-11e7-862d-f227709dad4a.png)

**Comment by mg2dael** [comment]
These are updated in stage, please test them.

Our QA team did some testing and had one question on expected behavior.  When they used membercenter.connextData.referrerType = "Social" for testing it behaved as expected when clicking an article from the Facebook Newsfeed or from Twitter. However, if they clicked a link sent to them through Facebook Messenger it behaved as if the user was NOT Social.  Is this correct behavior?

**Comment by kamini1208** [comment]
good question Dael. I don't think that was ever specified in the requirements -- i will follow up.  thanks. +K :)

**Comment by mg2dael** [comment]
@kamini1208 If it helps, here's the article @NatalliaMikhailava and our dev team used when solving for this issue on a different product https://www.ohow.co/facebook-referrals-l-lm-m-google-analytics/

**Comment by kamini1208** [comment]
closing ticket
