### ISSUE TITLE
Roadblock can be closed, need to prevent

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#22]
Roadblock can be closed, need to prevent

**Comment by mkoza178** [comment]
TS 6174

**Comment by mg2dael** [comment]
We've pushed an update to address this in production.  However, we can't retroactively apply it to saved templates so you'll need to recreate any paywalls that you don't want to be closable.

**Comment by gborders** [comment]
New roadblock template created

**Comment by mg2dael** [comment]
@kamini1208 Can we close this issue?

**Comment by kamini1208** [comment]
closing ticket
