### ISSUE TITLE
Trim feature is distorting story page, we can use blurred until item is resolved.

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#23]
Trim feature is distorting story page, we can use blurred until item is resolved.

**Comment by mg2dael** [comment]
This is caused by how your webpages are structured.  There's nothing the ConneXt team can do to fix it, unfortunately.

**Comment by mg2dael** [comment]
@kamini1208 Can we close this issue?

**Comment by gborders** [comment]
Yes
