### ISSUE TITLE
"Detect Ad Block" causing issues

### ISSUE THREAD

**Issue by sframe** [mg2connext/connext#29]
Hi @mg2dael & @mkoza178:

The Newspaper Folks are noticing rogue DOM elements being dynamically inserted onto the their web pages with Connext.

e.g. http://preview-dev.myajc.com/news/holly-second-story-june-this-one-has-extra-long-ridiculous-headline-for-testing-monectally/526G12zspzSrxtp5eMd6yJ/

```html
<div class="adsbox" id="TestAdBlock">&nbsp;</div>
<div class="adsbox" id="TestAdBlock">&nbsp;</div>
```

Appears to be caused by this snippet of code from connext:
```javascript
Connext = function(n) {
    function v() {
        var n = document.createElement("div");
        n.innerHTML = "&nbsp;";
        n.className = "adsbox"; # <-- Here!
        n.id = "TestAdBlock";
        document.body.appendChild(n)
    }
    #...
}
```

Please advise if this is a configuration issue on our end or if something needs to be fixed. Causing a bit of a headache for the CMS team. :|

Thanks!

**Comment by mg2dael** [comment]
Hi @sframe 
Your guess is correct that that's coming from ConneXt.  It's how we're detecting ad blockers. Basically we're tricking them into removing that div and, if the div is gone we know to treat the user as if they have an ad blocker.

**Comment by lmai83** [comment]
Hey @mg2dael - 
Would there be a workaround to getting rid of the whitespace circled here? 
![image](https://user-images.githubusercontent.com/20074524/28123329-bb7b4446-66ee-11e7-88d7-31c6d838a092.png)

**Comment by mg2dael** [comment]
@lmai83 Can you send us a URL where we can see this ourselves and look into it?

**Comment by lmai83** [comment]
@mg2dael Here you go!

here is a link from QA:  http://preview-qa.myajc.com/news/life-with-gracie-for-mjcca-league-softball-player-years-the-mound-isn-enough/526G12zspzSrxtp5eMd6yJ/
 
And from Dev: http://preview-dev.myajc.com/news/holly-second-story-june-this-one-has-extra-long-ridiculous-headline-for-testing-monectally/526G12zspzSrxtp5eMd6yJ/

**Comment by mg2dael** [comment]
Thanks @lmai83!
I suspect we'll have to alter what we're putting on the page for the ad blockers to remove. Our lead developer is back on Monday and we'll ask him to look into alternatives then.

**Comment by lmai83** [comment]
Thanks for the update, @mg2dael! I'll let the CMS team know.

**Comment by lmai83** [comment]
Hey @mg2dael - can we get an update on this one? Asking for the CMS team. TIA! 
EDIT: You know what - I just realized that today is Monday you're referring to. My bad, Dael! I'll wait till tomorrow :)

**Comment by mg2dael** [comment]
Hi Lan,

Nothing yet.  He was working through emails and some other open items, including some that seemed like they would effect PBP tomorrow.  I’m hoping he gets to look at this tomorrow.

-Dael

-------------------------------------------------------
Dael Jackson
Product/Project Manager
Marketing G2, LLC
Office: (267) 657-0078
djackson@marketingg2.com<mailto:djackson@marketingg2.com>
Results through Marketing Intelligence
[10533717_726233880763523_5240594632369260714_n]<http://marketingg2.com/>
Follow Marketing G2:
[Facebook Icon]<https://www.facebook.com/MarketingG2/>[Twitter Icon]<https://twitter.com/MarketingG2>[LinkedIn Icon]<https://www.linkedin.com/company-beta/1285481/>

**Comment by mg2dael** [comment]
@lmai83 An update: we think we've got a fix. We're testing internally.

**Comment by lmai83** [comment]
Thanks @mg2dael - I'll relay back to the CMS team.

**Comment by mg2dael** [comment]
@lmai83 Can we close this?  I think we're good here, but I wanted to confirm.

**Comment by lmai83** [comment]
@mg2dael - I'm checking with the Newspaper team and can update it whenever they get back with me!

**Comment by lmai83** [comment]
Newspaper Team says it's no longer an issue - thank you. @mg2dael!
