### ISSUE TITLE
debug UI incognito

### ISSUE THREAD

**Issue by sframe** [mg2connext/connext#31]
Hey @mg2dael,

@kamini1208 noticed something weird with the Connext debugger UI in Chrome in incognito mode. Seems like a new issue, so just checking if anything is planned on your end.

![screen shot 2017-07-21 at 9 32 11 am](https://user-images.githubusercontent.com/1569307/28466359-220e8080-6dfa-11e7-8c83-decb8dbdd224.png)
![screen shot 2017-07-21 at 9 33 29 am](https://user-images.githubusercontent.com/1569307/28466360-220f3d2c-6dfa-11e7-8762-919e49184b3f.png)

Thanks!

**Comment by mg2dael** [comment]
Thanks @sframe and @kamini1208 Definitely not planned and definitely weird. Looks like it doesn't have to be incognito either, just anywhere.  It doesn't happen on non-member center pages, though.  I'll throw it in the bug list.

**Comment by mg2dael** [comment]
@sframe @kamini1208 I think we've got this fixed now. Can you re-check?

**Comment by kamini1208** [comment]
@sframe @mg2dael :  yep.  it is fix.  will close issue.  thanks.
