### ISSUE TITLE
[eCommerce Abandonment]: Debugger does not display on Android device

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#4]
the Debug Details does NOT display on any Android Device using the Native browser or Chrome.  Verified on Samsung Galaxy S6 (v6.0.1), Droid Turbo 2 (v. 5.1.1)

No presentation displays as well.

**Comment by mg2dael** [comment]
Got it, thanks.

**Comment by mg2dael** [comment]
We're having a hard time reproducing, though we don't have the exact devices you mentioned. We tried on a Samsung Galaxy S5 on v6.0.1 and had no problems. Are you using an emulator or a physical device?

**Comment by mkoza178** [comment]
Dael,

Kamini is saying these are physical devices she is testing on.

**Comment by kamini1208** [comment]
Same here Dael - I am verifying the test MG2 URL: https://test-cox-paypanel-ajc.subscriberconcierge.com/subscriptionpanel

**Comment by mkoza178** [comment]
I tested using a physical S6 today and am not seeing issues on the Test site. I can see the debugger.

**Comment by mkoza178** [comment]
Hey guys,

Any concerns with this still? We have been unable to reproduce.

**Comment by kamini1208** [comment]
Closing issue.  Can view debugger on all Android device.
