### ISSUE TITLE
[Targeted Messaging] Inline Ad not displaying on Mobile

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#5]
TM Ad not displaying on Mobile.  On the web, it displays right below the 'Customer Service' on every page, however; on the mobile, there is only one customer service section which is at the end of the page.  See Screen Shots: 
web: ![screen shot 2016-12-12 at 2 17 07 pm]
(https://cloud.githubusercontent.com/assets/20052632/21112953/b471bd1c-c075-11e6-9f71-aa5bcf254fc6.png)
mobile: ![screen shot 2016-12-12 at 2 17 59 pm](https://cloud.githubusercontent.com/assets/20052632/21112978/d8f790a8-c075-11e6-8315-7141973a11c4.png)

**Comment by mg2dael** [comment]
We investigated this and don't believe it's a ConneXt problem. If you look at the member center site, the responsive design you're using hides the area that contains the inline Flittz. We tried putting the inline in an area that stays present on mobile devices and we can still see it: http://prntscr.com/diug1r We also checked on an Android and iPhone that we could see it.

**Comment by kamini1208** [comment]
Closing out this issue - not a MG2 issue.  I have opened a Github/V1 Issue with the MC team (Github 653/D-07349)
