### ISSUE TITLE
[Targeted Messaging] the Ads are not displaying on each page

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#6]
Targeted Messaging ads are not displaying on each page (Your Account, Newsletters, Text Alerts, and Manage Subscription). 

NOTE for Dael: Gwen mentioned that there may be a potential workaround - please work with Gwen.

**Comment by mkoza178** [comment]
We passed off to Gwen, via email a way to display ads based off the tab selected.
Gwen do you have any further questions on this?

**Comment by kamini1208** [comment]
Closing issue.  Conversations/Ads are displaying on all pages.
