### ISSUE TITLE
[Targeted Messaging]: In MG2 Admin, template needs resizing

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#7]
In MG2 Admin, only the 1st template is sized correct, the other 3 needs re-sizing.
template 1: correct size
![screen shot 2016-12-12 at 2 31 53 pm](https://cloud.githubusercontent.com/assets/20052632/21113495/cd763dea-c077-11e6-904a-4010b7b8046c.png)
template 2: needs resizing along with template 3 and 4.
![screen shot 2016-12-12 at 2 32 41 pm](https://cloud.githubusercontent.com/assets/20052632/21113518/e739ba2c-c077-11e6-8941-cb9479f4fdf1.png)

**Comment by NatalliaMikhailava** [comment]
Added a TFS for that

**Comment by mkoza178** [comment]
This should be resolved as well. We added small templates. http://prnt.sc/dk7prv

**Comment by kamini1208** [comment]
closing issue.  verified template resized.
