### ISSUE TITLE
[Targeted Messaging] On Newsletters page, two ads are displaying

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#9]
[Targeted Messaging] On Newsletters page, two ads are displaying.  See Screen Shot:
http://membercenter-dev-connext.aws.cmgdigital.com/newsletters
<img width="300" alt="screen shot 2016-12-14 at 3 53 11 pm" src="https://cloud.githubusercontent.com/assets/20052632/21200678/25f21dd2-c216-11e6-8e20-e44399bedc36.png">

**Comment by mg2dael** [comment]
Hi Kamini!
Can you send a screenshot with the debug panel? I'm not seeing it now so I'm wondering if you were on a different conversation then it's on now.
Thanks!

**Comment by kamini1208** [comment]
Dael, attached screen shot of the dubugger.
![screen shot 2016-12-15 at 10 58 47 am](https://cloud.githubusercontent.com/assets/20052632/21231253/974b0f44-c2b5-11e6-87d1-93090797637b.png)

**Comment by kamini1208** [comment]
closing issue.  this was fixed with MG2 admin configuration.
